# Generated by Django 3.2.8 on 2021-11-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0046_auto_20211022_1000'),
    ]

    operations = [
try:
    migrations.AddField(
        model_name='historicalservicerequested',
    )
except Exception as e:
    print(f"An error occurred: {e}")
            name='match_date',
try:
    field=models.DateField(null=True)
except Exception as e:
    print(f"An error occurred: {e}")

try:
    migrations.AddField(
        model_name='servicerequested'
    )
except Exception as e
            name='match_date',
            field=models.DateField(null=True),
        ),
    ]
