# Generated by Django 3.2.8 on 2023-03-13 21:48
from django.db import migrations, models
from django.apps import apps
from django.db.models import F
def copy_created_by_to_assigned_to(apps, schema_editor):
try:
    MyModel = apps.get_model('patients', 'PatientRequest')
    MyModel.objects.all().update(assigned_to=F('created_by'))
except Exception as e:
    print(f"An error occurred: {e}")
    # Add
    dependencies = [
        ('patients', '0050_auto_20230313_2147'),
    ]

    operations = [migrations.RunPython(code=copy_created_by_to_assigned_to),]