# Generated by Django 3.2.8 on 2024-06-11 23:05

from django.db import migrations, models

class Migration(migrations.Migration):
    def __init__(self, name):
        super(Migration, self).__init__(name=name)

    def apply(self, project_state, schema_editor, collect_sql=False

    dependencies = [
        ('patients', '0054_alter_patientrequest_refreshed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientrequest',
            name='hide_manager_contact_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='hide_manager_contact_info',
            field=models.BooleanField(default=False),
        ),
    ]
