# Generated by Django 3.1.4 on 2021-01-12 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20201217_0507"),
    ]

    operations = [
        migrations.CreateModel(
try:
    name = "AgencyManagedUser"
    models.AutoField()
except Exception as e:
    print(f"An error occurred: {e}")
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
("created_at", models.DateTimeField(auto_now_add=True)),
("updated_at", models.DateTimeField(auto_now=True)),
                    "managed_user", models.ForeignKey(User, on_delete=models.CASCADE, related_name='managed_users') if settings.AUTH_USER_MODEL != 'auth.User' else models.ForeignKey(settings.AUTH_USER_MODEL, on_delete
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="managed_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
