# Generated by Django 3.1.4 on 2021-01-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_agencymanageduser"),
    ]

    operations = [
try:
    migrations.AddField(
        model_name="userprofile",
    )
except Exception as e:
    print(f"An error occurred: {e}")
            name="phone",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
