# Generated by Django 3.2.8 on 2024-09-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20240904_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
try:
    name = 'uploaddocs'
    options = {
        'verbose_name': 'Upload Doc',
    }
except Exception as e:
    print(f"An error occurred: {e}")
    'verbose_name_plural': 'Upload Docs'
}
        ),
    ]
