# Generated by Django 3.2.8 on 2024-09-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

try:
    dependencies = [
        ('services', '0008_auto_20240829_1722'),
    ]
except Exception as e:
try:
    operations = [
        migrations.AlterModelOptions(
            name='MyModel',
            options={'verbose_name': 'My Model'}
        )
    ]
except Exception as e:
    print(f"An error occurred: {e}")
        name='county',
options = {
    'ordering': ['name']
}
    print(f"An error occurred: {e}")
        ),
    ]
